version: 2
updates:
  - package-ecosystem: npm
    directories:
      - "/legal-semantic-search"
      - "/namespace-notes/client"
      - "/namespace-notes/server"
      - "/pinecone-assistant"
      - "/shop-the-look"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
  - package-ecosystem: pip
    directory: "/shop-the-look"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
